apiVersion: v1
kind: Service
metadata:
  name: bookbug-frontend-service
  namespace: bookbug
spec:
  selector:
    app: bookbug-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
